### ISSUE TITLE
error when not specifying OPEN_AI_API

### ISSUE THREAD

**Issue by justaddcoffee** [hrshdhgd/kg-chat#9]
When I run kg chat with no OPEN_AI_API var set (but CBORG_API_KEY set), I get this error: 

```
(kg-chat-py3.11) ~/PythonProject/kg-chat main $ CBORG_API_KEY=`cat ~/cborg.key` kg app 
Traceback (most recent call last):
  File "/Users/jtr4v/PythonProject/kg-chat/.venv/bin/kg", line 3, in <module>
    from kg_chat.cli import main
  File "/Users/jtr4v/PythonProject/kg-chat/src/kg_chat/cli.py", line 28, in <module>
    ALL_AVAILABLE_MODELS = get_openai_models() + get_ollama_models() + get_anthropic_models() + get_lbl_cborg_models()
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jtr4v/PythonProject/kg-chat/src/kg_chat/utils.py", line 215, in get_openai_models
    return sorted_model_ids
           ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'sorted_model_ids' where it is not associated with a value
(kg-chat-py3.11) ~/PythonProject/kg-chat main $ grep -i provider README.md 
| **LLM Provider**            | **Models**                                                                                   |
(kg-chat-py3.11) ~/PythonProject/kg-chat main $ CBORG_API_KEY=`cat ~/cborg.key` poetry run kg app --data-dir data
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/jtr4v/PythonProject/kg-chat/src/kg_chat/cli.py", line 28, in <module>
    ALL_AVAILABLE_MODELS = get_openai_models() + get_ollama_models() + get_anthropic_models() + get_lbl_cborg_models()
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jtr4v/PythonProject/kg-chat/src/kg_chat/utils.py", line 215, in get_openai_models
    return sorted_model_ids
           ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'sorted_model_ids' where it is not associated with a value
```

But this is fixed when I set OPENAI_API_KEY:

```
(kg-chat-py3.11) ~/PythonProject/kg-chat main $ OPENAI_API_KEY=`cat ~/openai.key.another` CBORG_API_KEY=`cat ~/cborg.key` kg app --data-dir ./data/
/Users/jtr4v/PythonProject/kg-chat/.venv/lib/python3.11/site-packages/duckdb_engine/__init__.py:174: DuckDBEngineWarning: duckdb-engine doesn't yet support reflection on indices
  warnings.warn(
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'kg_chat.app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8050
Press CTRL+C to quit
```

I'm on `main`, commit 63d92e10adbd5dc550cd52911c7d4144dfdd61c2

**Comment by hrshdhgd** [comment]
Oversight on my part. Thanks for making the issue !! Please review #12
